parserOptions:
  ecmaVersion: 2015
  sourceType: 'module'

rules:
  semi: error
  indent:
  - error
  - 2
  - SwitchCase: 1

env:
  es6: true
  browser: true
  commonjs: true

extends: 'htmlacademy/es6'
